/**
 * Mini-Games Database
 * Contém todos os mini-games disponíveis por matéria
 */

import type { MiniGame } from '@/types/minigames';

export const MINI_GAMES: MiniGame[] = [
  // ========== MATEMÁTICA ==========
  {
    id: 'mat-quiz-1',
    title: 'Quiz de Álgebra',
    description: 'Teste seus conhecimentos sobre equações básicas',
    type: 'quiz',
    subject: 'math',
    difficulty: 'médio',
    duration: 300,
    xpReward: 100,
    questions: [
      {
        id: '1',
        text: 'Qual é o valor de x em: 2x + 5 = 13?',
        type: 'quiz',
        options: ['2', '4', '6', '8'],
        correctAnswer: '4',
      },
      {
        id: '2',
        text: 'O que é uma função?',
        type: 'quiz',
        options: [
          'Uma relação que não existe',
          'Uma relação entre dois conjuntos',
          'Um número',
          'Uma letra',
        ],
        correctAnswer: 'Uma relação entre dois conjuntos',
      },
      {
        id: '3',
        text: 'Qual é a área de um círculo com raio 3?',
        type: 'quiz',
        options: ['6π', '9π', '12π', '3π'],
        correctAnswer: '9π',
      },
    ],
  },
  {
    id: 'mat-tf-1',
    title: 'Verdadeiro ou Falso - Geometria',
    description: 'Decida se as afirmações sobre geometria são verdadeiras',
    type: 'truefalse',
    subject: 'math',
    difficulty: 'fácil',
    duration: 180,
    xpReward: 50,
    questions: [
      {
        id: '1',
        text: 'Um quadrado tem 4 lados iguais',
        type: 'truefalse',
        correctAnswer: 'verdadeiro',
      },
      {
        id: '2',
        text: 'Um triângulo tem 4 ângulos',
        type: 'truefalse',
        correctAnswer: 'falso',
      },
      {
        id: '3',
        text: 'A soma dos ângulos de um triângulo é 180°',
        type: 'truefalse',
        correctAnswer: 'verdadeiro',
      },
    ],
  },

  // ========== PORTUGUÊS ==========
  {
    id: 'port-quiz-1',
    title: 'Quiz de Literatura',
    description: 'Teste seus conhecimentos sobre obras literárias brasileiras',
    type: 'quiz',
    subject: 'portuguese',
    difficulty: 'médio',
    duration: 300,
    xpReward: 100,
    questions: [
      {
        id: '1',
        text: 'Quem escreveu "Grande Sertão: Veredas"?',
        type: 'quiz',
        options: ['Machado de Assis', 'Guimarães Rosa', 'Carlos Drummond', 'Jorge Amado'],
        correctAnswer: 'Guimarães Rosa',
      },
      {
        id: '2',
        text: 'O que é uma metáfora?',
        type: 'quiz',
        options: [
          'Uma comparação com "como"',
          'Uma comparação sem a palavra "como"',
          'Uma repetição de sons',
          'Uma pergunta retórica',
        ],
        correctAnswer: 'Uma comparação sem a palavra "como"',
      },
      {
        id: '3',
        text: 'Qual é o gênero de "O Cortiço" de Aluísio Azevedo?',
        type: 'quiz',
        options: ['Romantismo', 'Realismo', 'Modernismo', 'Barroco'],
        correctAnswer: 'Realismo',
      },
    ],
  },
  {
    id: 'port-fill-1',
    title: 'Preencha as Lacunas - Gramática',
    description: 'Complete as frases com as palavras corretas',
    type: 'fillblank',
    subject: 'portuguese',
    difficulty: 'fácil',
    duration: 240,
    xpReward: 75,
    questions: [
      {
        id: '1',
        text: 'O gato _____ no telhado.',
        type: 'fillblank',
        correctAnswer: 'está',
      },
      {
        id: '2',
        text: 'Eu _____ um livro ontem.',
        type: 'fillblank',
        correctAnswer: 'li',
      },
      {
        id: '3',
        text: 'Ela _____ muito bem.',
        type: 'fillblank',
        correctAnswer: 'canta',
      },
    ],
  },

  // ========== CIÊNCIAS ==========
  {
    id: 'cie-quiz-1',
    title: 'Quiz de Biologia',
    description: 'Teste seus conhecimentos sobre a célula',
    type: 'quiz',
    subject: 'science',
    difficulty: 'médio',
    duration: 300,
    xpReward: 100,
    questions: [
      {
        id: '1',
        text: 'Qual é a unidade básica da vida?',
        type: 'quiz',
        options: ['Molécula', 'Célula', 'Átomo', 'Organela'],
        correctAnswer: 'Célula',
      },
      {
        id: '2',
        text: 'O que faz a mitocôndria?',
        type: 'quiz',
        options: [
          'Produz energia',
          'Armazena DNA',
          'Produz proteína',
          'Controla o pH',
        ],
        correctAnswer: 'Produz energia',
      },
      {
        id: '3',
        text: 'Qual organela contém o DNA?',
        type: 'quiz',
        options: ['Ribossomo', 'Núcleo', 'Mitocôndria', 'Lisossoma'],
        correctAnswer: 'Núcleo',
      },
    ],
  },
  {
    id: 'cie-tf-1',
    title: 'Verdadeiro ou Falso - Física',
    description: 'Decida se as afirmações sobre física são verdadeiras',
    type: 'truefalse',
    subject: 'science',
    difficulty: 'médio',
    duration: 240,
    xpReward: 75,
    questions: [
      {
        id: '1',
        text: 'A velocidade da luz é constante em qualquer meio',
        type: 'truefalse',
        correctAnswer: 'falso',
      },
      {
        id: '2',
        text: 'A energia não pode ser criada ou destruída',
        type: 'truefalse',
        correctAnswer: 'verdadeiro',
      },
      {
        id: '3',
        text: 'A gravidade é mais forte que as outras forças fundamentais',
        type: 'truefalse',
        correctAnswer: 'falso',
      },
    ],
  },

  // ========== HISTÓRIA ==========
  {
    id: 'hist-quiz-1',
    title: 'Quiz - Independência do Brasil',
    description: 'Teste seus conhecimentos sobre a independência brasileira',
    type: 'quiz',
    subject: 'history',
    difficulty: 'médio',
    duration: 300,
    xpReward: 100,
    questions: [
      {
        id: '1',
        text: 'Em que ano o Brasil se tornou independente?',
        type: 'quiz',
        options: ['1808', '1815', '1822', '1889'],
        correctAnswer: '1822',
      },
      {
        id: '2',
        text: 'Quem proclamou a independência do Brasil?',
        type: 'quiz',
        options: ['D. Pedro I', 'D. João VI', 'Tiradentes', 'José Bonifácio'],
        correctAnswer: 'D. Pedro I',
      },
      {
        id: '3',
        text: 'Onde D. Pedro gritou "Independência ou Morte"?',
        type: 'quiz',
        options: ['Rio de Janeiro', 'Ipiranga', 'Bahia', 'Minas Gerais'],
        correctAnswer: 'Ipiranga',
      },
    ],
  },

  // ========== INGLÊS ==========
  {
    id: 'ing-quiz-1',
    title: 'Quiz - Phrasal Verbs',
    description: 'Teste seus conhecimentos sobre phrasal verbs em inglês',
    type: 'quiz',
    subject: 'english',
    difficulty: 'médio',
    duration: 300,
    xpReward: 100,
    questions: [
      {
        id: '1',
        text: 'O que significa "Give up"?',
        type: 'quiz',
        options: ['Entregar', 'Desistir', 'Dar em cima', 'Aumentar'],
        correctAnswer: 'Desistir',
      },
      {
        id: '2',
        text: 'Complete: "I ___ up at 7am every day"',
        type: 'quiz',
        options: ['wake', 'woke', 'get', 'got'],
        correctAnswer: 'wake',
      },
      {
        id: '3',
        text: 'Qual é o pronome correto: "She and ___ are friends"',
        type: 'quiz',
        options: ['me', 'I', 'myself', 'my'],
        correctAnswer: 'I',
      },
    ],
  },
  {
    id: 'ing-fill-1',
    title: 'Preencha as Lacunas - Inglês Básico',
    description: 'Complete as frases em inglês',
    type: 'fillblank',
    subject: 'english',
    difficulty: 'fácil',
    duration: 240,
    xpReward: 75,
    questions: [
      {
        id: '1',
        text: 'My name _____ John.',
        type: 'fillblank',
        correctAnswer: 'is',
      },
      {
        id: '2',
        text: 'She _____ to school every day.',
        type: 'fillblank',
        correctAnswer: 'goes',
      },
      {
        id: '3',
        text: 'They are _____ the park.',
        type: 'fillblank',
        correctAnswer: 'in',
      },
    ],
  },

  // ========== GEOGRAFIA ==========
  {
    id: 'geo-quiz-1',
    title: 'Quiz de Capitais',
    description: 'Identifique as capitais dos países',
    type: 'quiz',
    subject: 'geography',
    difficulty: 'médio',
    duration: 300,
    xpReward: 100,
    questions: [
      {
        id: '1',
        text: 'Qual é a capital do Brasil?',
        type: 'quiz',
        options: ['São Paulo', 'Brasília', 'Rio de Janeiro', 'Salvador'],
        correctAnswer: 'Brasília',
      },
      {
        id: '2',
        text: 'Qual é a capital da França?',
        type: 'quiz',
        options: ['Lyon', 'Marselha', 'Paris', 'Toulouse'],
        correctAnswer: 'Paris',
      },
      {
        id: '3',
        text: 'Qual é a capital do Japão?',
        type: 'quiz',
        options: ['Osaka', 'Tóquio', 'Kyoto', 'Hiroshima'],
        correctAnswer: 'Tóquio',
      },
    ],
  },
  {
    id: 'geo-tf-1',
    title: 'Verdadeiro ou Falso - Geografia Física',
    description: 'Teste seus conhecimentos sobre geografia',
    type: 'truefalse',
    subject: 'geography',
    difficulty: 'médio',
    duration: 240,
    xpReward: 75,
    questions: [
      {
        id: '1',
        text: 'O Nilo é o rio mais comprido do mundo.',
        type: 'truefalse',
        correctAnswer: 'Verdadeiro',
      },
      {
        id: '2',
        text: 'A Ásia é o continente com maior população.',
        type: 'truefalse',
        correctAnswer: 'Verdadeiro',
      },
      {
        id: '3',
        text: 'O Saara é o deserto mais seco do mundo.',
        type: 'truefalse',
        correctAnswer: 'Verdadeiro',
      },
    ],
  },

  // ========== EDUCAÇÃO FÍSICA ==========
  {
    id: 'ef-quiz-1',
    title: 'Quiz de Esportes',
    description: 'Teste seus conhecimentos sobre esportes',
    type: 'quiz',
    subject: 'physical-ed',
    difficulty: 'fácil',
    duration: 240,
    xpReward: 75,
    questions: [
      {
        id: '1',
        text: 'Quantos jogadores tem um time de futebol em campo?',
        type: 'quiz',
        options: ['9', '10', '11', '12'],
        correctAnswer: '11',
      },
      {
        id: '2',
        text: 'Qual é a duração de um jogo de basquete?',
        type: 'quiz',
        options: ['30 min', '40 min', '45 min', '60 min'],
        correctAnswer: '40 min',
      },
      {
        id: '3',
        text: 'Em que esporte se usa uma raquete e uma bola pequena?',
        type: 'quiz',
        options: ['Badminton', 'Vôlei', 'Basquete', 'Futebol'],
        correctAnswer: 'Badminton',
      },
    ],
  },
  {
    id: 'ef-fill-1',
    title: 'Preencha - Saúde e Bem-estar',
    description: 'Complete as frases sobre saúde',
    type: 'fillblank',
    subject: 'physical-ed',
    difficulty: 'fácil',
    duration: 200,
    xpReward: 50,
    questions: [
      {
        id: '1',
        text: 'A atividade física regular melhora a saúde do _____ e pulmões.',
        type: 'fillblank',
        correctAnswer: 'coração',
      },
      {
        id: '2',
        text: 'Um adulto deve dormir entre _____ e 8 horas por noite.',
        type: 'fillblank',
        correctAnswer: '7',
      },
      {
        id: '3',
        text: 'O alongamento ajuda a _____ a flexibilidade dos músculos.',
        type: 'fillblank',
        correctAnswer: 'aumentar',
      },
    ],
  },

  // ========== ARTE ==========
  {
    id: 'arte-quiz-1',
    title: 'Quiz de Artistas Famosos',
    description: 'Identifique obras de grandes artistas',
    type: 'quiz',
    subject: 'art',
    difficulty: 'médio',
    duration: 300,
    xpReward: 100,
    questions: [
      {
        id: '1',
        text: 'Quem pintou a Mona Lisa?',
        type: 'quiz',
        options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'],
        correctAnswer: 'Leonardo da Vinci',
      },
      {
        id: '2',
        text: 'Qual artista cortou sua própria orelha?',
        type: 'quiz',
        options: ['Picasso', 'Van Gogh', 'Dalí', 'Monet'],
        correctAnswer: 'Van Gogh',
      },
      {
        id: '3',
        text: 'Qual técnica usa pequenos pontos de cor?',
        type: 'quiz',
        options: ['Cubismo', 'Pontilhismo', 'Surrealismo', 'Impressionismo'],
        correctAnswer: 'Pontilhismo',
      },
    ],
  },
  {
    id: 'arte-fill-1',
    title: 'Preencha - Cores e Formas',
    description: 'Complete as frases sobre arte',
    type: 'fillblank',
    subject: 'art',
    difficulty: 'fácil',
    duration: 240,
    xpReward: 75,
    questions: [
      {
        id: '1',
        text: 'As cores primárias são vermelho, azul e _____.',
        type: 'fillblank',
        correctAnswer: 'amarelo',
      },
      {
        id: '2',
        text: 'Uma _____ é uma forma com três lados.',
        type: 'fillblank',
        correctAnswer: 'triângulo',
      },
      {
        id: '3',
        text: 'A _____ é a técnica de desenho com lápis ou carvão.',
        type: 'fillblank',
        correctAnswer: 'grafite',
      },
    ],
  },

  // ========== MÚSICA ==========
  {
    id: 'mus-quiz-1',
    title: 'Quiz de Notas Musicais',
    description: 'Teste seus conhecimentos sobre música',
    type: 'quiz',
    subject: 'music',
    difficulty: 'médio',
    duration: 300,
    xpReward: 100,
    questions: [
      {
        id: '1',
        text: 'Quantas notas tem a escala musical básica?',
        type: 'quiz',
        options: ['5', '7', '8', '12'],
        correctAnswer: '7',
      },
      {
        id: '2',
        text: 'Qual é a nota mais alta da escala?',
        type: 'quiz',
        options: ['Dó', 'Ré', 'Si', 'Fá'],
        correctAnswer: 'Si',
      },
      {
        id: '3',
        text: 'Qual instrumento tem 88 teclas?',
        type: 'quiz',
        options: ['Violino', 'Piano', 'Flauta', 'Trompete'],
        correctAnswer: 'Piano',
      },
    ],
  },
  {
    id: 'mus-fill-1',
    title: 'Preencha - Instrumentos Musicais',
    description: 'Complete as frases sobre instrumentos',
    type: 'fillblank',
    subject: 'music',
    difficulty: 'fácil',
    duration: 240,
    xpReward: 75,
    questions: [
      {
        id: '1',
        text: 'A _____ é um instrumento de sopro feito de madeira.',
        type: 'fillblank',
        correctAnswer: 'flauta',
      },
      {
        id: '2',
        text: 'O _____ é um instrumento de corda dedilhada.',
        type: 'fillblank',
        correctAnswer: 'violão',
      },
      {
        id: '3',
        text: 'A _____ tem peles que são percutidas com baquetas.',
        type: 'fillblank',
        correctAnswer: 'bateria',
      },
    ],
  },

  // ========== FILOSOFIA ==========
  {
    id: 'filos-quiz-1',
    title: 'Quiz de Filósofos Antigos',
    description: 'Teste seus conhecimentos sobre filósofos',
    type: 'quiz',
    subject: 'philosophy',
    difficulty: 'médio',
    duration: 300,
    xpReward: 100,
    questions: [
      {
        id: '1',
        text: 'Qual filósofo grego criou a Academia?',
        type: 'quiz',
        options: ['Sócrates', 'Platão', 'Aristóteles', 'Epicuro'],
        correctAnswer: 'Platão',
      },
      {
        id: '2',
        text: 'Qual é o lema da filosofia?',
        type: 'quiz',
        options: [
          'Ganhar dinheiro',
          'Amar dinheiro',
          'Conhecer a ti mesmo',
          'Ser feliz',
        ],
        correctAnswer: 'Conhecer a ti mesmo',
      },
      {
        id: '3',
        text: 'Quem disse "Penso, logo existo"?',
        type: 'quiz',
        options: ['Kant', 'Descartes', 'Hume', 'Wittgenstein'],
        correctAnswer: 'Descartes',
      },
    ],
  },
  {
    id: 'filos-fill-1',
    title: 'Preencha - Conceitos Filosóficos',
    description: 'Complete as frases sobre filosofia',
    type: 'fillblank',
    subject: 'philosophy',
    difficulty: 'médio',
    duration: 240,
    xpReward: 75,
    questions: [
      {
        id: '1',
        text: 'A _____ é o estudo do bem e do mal.',
        type: 'fillblank',
        correctAnswer: 'ética',
      },
      {
        id: '2',
        text: 'A _____ estuda a natureza da realidade.',
        type: 'fillblank',
        correctAnswer: 'metafísica',
      },
      {
        id: '3',
        text: 'A _____ estuda o conhecimento humano.',
        type: 'fillblank',
        correctAnswer: 'epistemologia',
      },
    ],
  },

  // ========== RELIGIÃO/ÉTICA ==========
  {
    id: 'ética-quiz-1',
    title: 'Quiz de Valores Éticos',
    description: 'Teste seus conhecimentos sobre ética',
    type: 'quiz',
    subject: 'ethics',
    difficulty: 'médio',
    duration: 300,
    xpReward: 100,
    questions: [
      {
        id: '1',
        text: 'Qual é um dos principais valores universais?',
        type: 'quiz',
        options: ['Ganância', 'Honestidade', 'Egoísmo', 'Inveja'],
        correctAnswer: 'Honestidade',
      },
      {
        id: '2',
        text: 'O que significa respeito?',
        type: 'quiz',
        options: [
          'Ignorar os outros',
          'Reconhecer a dignidade de todos',
          'Dominar os outros',
          'Ser melhor que os outros',
        ],
        correctAnswer: 'Reconhecer a dignidade de todos',
      },
      {
        id: '3',
        text: 'Qual religião prega a compaixão e o perdão?',
        type: 'quiz',
        options: ['Muitas delas', 'Nenhuma', 'Só o cristianismo', 'Só o budismo'],
        correctAnswer: 'Muitas delas',
      },
    ],
  },
  {
    id: 'ética-fill-1',
    title: 'Preencha - Princípios de Convivência',
    description: 'Complete as frases sobre convivência',
    type: 'fillblank',
    subject: 'ethics',
    difficulty: 'fácil',
    duration: 240,
    xpReward: 75,
    questions: [
      {
        id: '1',
        text: 'A _____ é o respeito pelos direitos dos outros.',
        type: 'fillblank',
        correctAnswer: 'tolerância',
      },
      {
        id: '2',
        text: 'A _____ significa ser leal e confiável.',
        type: 'fillblank',
        correctAnswer: 'honestidade',
      },
      {
        id: '3',
        text: 'A _____ nos ajuda a entender as emoções dos outros.',
        type: 'fillblank',
        correctAnswer: 'empatia',
      },
    ],
  },

  // ========== INFORMÁTICA ==========
  {
    id: 'info-quiz-1',
    title: 'Quiz de Programação',
    description: 'Teste seus conhecimentos de programação',
    type: 'quiz',
    subject: 'computer-science',
    difficulty: 'médio',
    duration: 300,
    xpReward: 100,
    questions: [
      {
        id: '1',
        text: 'Qual linguagem é conhecida como "A Linguagem da Web"?',
        type: 'quiz',
        options: ['Python', 'Java', 'JavaScript', 'C++'],
        correctAnswer: 'JavaScript',
      },
      {
        id: '2',
        text: 'O que é um algoritmo?',
        type: 'quiz',
        options: [
          'Um tipo de computador',
          'Uma sequência de passos para resolver um problema',
          'Um programa de TV',
          'Um tipo de vírus',
        ],
        correctAnswer: 'Uma sequência de passos para resolver um problema',
      },
      {
        id: '3',
        text: 'Qual é a unidade básica de informação em um computador?',
        type: 'quiz',
        options: ['Byte', 'Bit', 'Megabyte', 'Gigabyte'],
        correctAnswer: 'Bit',
      },
    ],
  },
  {
    id: 'info-fill-1',
    title: 'Preencha - Conceitos de TI',
    description: 'Complete as frases sobre tecnologia',
    type: 'fillblank',
    subject: 'computer-science',
    difficulty: 'fácil',
    duration: 240,
    xpReward: 75,
    questions: [
      {
        id: '1',
        text: 'HTML é usado para criar a _____ de uma página web.',
        type: 'fillblank',
        correctAnswer: 'estrutura',
      },
      {
        id: '2',
        text: 'Um _____ é um programa malicioso que prejudica o computador.',
        type: 'fillblank',
        correctAnswer: 'vírus',
      },
      {
        id: '3',
        text: 'A _____ protege dados pessoais na internet.',
        type: 'fillblank',
        correctAnswer: 'segurança',
      },
    ],
  },

  // ========== ESPANHOL ==========
  {
    id: 'esp-quiz-1',
    title: 'Quiz de Vocabulário Espanhol',
    description: 'Teste seu vocabulário em espanhol',
    type: 'quiz',
    subject: 'spanish',
    difficulty: 'fácil',
    duration: 240,
    xpReward: 75,
    questions: [
      {
        id: '1',
        text: 'Como se diz "livro" em espanhol?',
        type: 'quiz',
        options: ['Libro', 'Lápiz', 'Mesa', 'Silla'],
        correctAnswer: 'Libro',
      },
      {
        id: '2',
        text: 'Como se diz "olá" em espanhol?',
        type: 'quiz',
        options: ['Adiós', 'Hola', 'Buenos días', 'Buenas noches'],
        correctAnswer: 'Hola',
      },
      {
        id: '3',
        text: 'Como se diz "obrigado" em espanhol?',
        type: 'quiz',
        options: ['De nada', 'Gracias', 'Por favor', 'Perdón'],
        correctAnswer: 'Gracias',
      },
    ],
  },
  {
    id: 'esp-fill-1',
    title: 'Preencha - Frases em Espanhol',
    description: 'Complete as frases em espanhol',
    type: 'fillblank',
    subject: 'spanish',
    difficulty: 'fácil',
    duration: 240,
    xpReward: 75,
    questions: [
      {
        id: '1',
        text: 'Mi nombre _____ Carlos.',
        type: 'fillblank',
        correctAnswer: 'es',
      },
      {
        id: '2',
        text: 'Yo _____ en Brasil.',
        type: 'fillblank',
        correctAnswer: 'vivo',
      },
      {
        id: '3',
        text: 'Ella _____ estudiante.',
        type: 'fillblank',
        correctAnswer: 'es',
      },
    ],
  },
];

