// Educational scenarios for each avatar
export interface Scenario {
    id: string;
    avatarId: string;
    title: string;
    description: string;
    difficulty: 'beginner' | 'intermediate' | 'advanced';
    category: string;
    initialPrompt: string;
    learningObjectives: string[];
    estimatedDuration: number; // in minutes
}

export const SCENARIOS: Scenario[] = [
    // ========== ENGLISH SCENARIOS (Sarah) ==========
    {
        id: 'en-airport',
        avatarId: 'tutor-ingles',
        title: 'At the Airport',
        description: 'Practice checking in, asking for directions, and handling common airport situations.',
        difficulty: 'beginner',
        category: 'Travel',
        initialPrompt: `You're at the airport check-in counter. I'm the airline staff. Let's practice checking in for your flight. Start by greeting me and telling me where you're flying to.`,
        learningObjectives: [
            'Airport vocabulary',
            'Asking for information',
            'Understanding directions',
        ],
        estimatedDuration: 10,
    },
    {
        id: 'en-restaurant',
        avatarId: 'tutor-ingles',
        title: 'Ordering at a Restaurant',
        description: 'Learn to order food, ask about menu items, and handle restaurant interactions.',
        difficulty: 'beginner',
        category: 'Daily Life',
        initialPrompt: `Welcome to our restaurant! I'm your server. What would you like to order today? Feel free to ask me about our menu.`,
        learningObjectives: [
            'Food vocabulary',
            'Making requests politely',
            'Asking questions about menu',
        ],
        estimatedDuration: 10,
    },
    {
        id: 'en-job-interview',
        avatarId: 'tutor-ingles',
        title: 'Job Interview Practice',
        description: 'Prepare for job interviews with common questions and professional language.',
        difficulty: 'intermediate',
        category: 'Professional',
        initialPrompt: `Hello! Thank you for coming in today. I'm the hiring manager. Tell me a bit about yourself and why you're interested in this position.`,
        learningObjectives: [
            'Professional vocabulary',
            'Talking about experience',
            'Answering interview questions',
        ],
        estimatedDuration: 15,
    },
    {
        id: 'en-shopping',
        avatarId: 'tutor-ingles',
        title: 'Shopping for Clothes',
        description: 'Practice asking for sizes, colors, trying on clothes, and making purchases.',
        difficulty: 'beginner',
        category: 'Daily Life',
        initialPrompt: `Hi! Welcome to our clothing store. I'm here to help you find what you need. What are you looking for today?`,
        learningObjectives: [
            'Clothing vocabulary',
            'Sizes and colors',
            'Making purchases',
        ],
        estimatedDuration: 10,
    },
    {
        id: 'en-doctor',
        avatarId: 'tutor-ingles',
        title: 'At the Doctor\'s Office',
        description: 'Learn to describe symptoms, understand medical advice, and communicate health concerns.',
        difficulty: 'intermediate',
        category: 'Health',
        initialPrompt: `Good morning! I'm Dr. Wilson. What brings you in today? Please describe how you're feeling.`,
        learningObjectives: [
            'Health vocabulary',
            'Describing symptoms',
            'Understanding medical advice',
        ],
        estimatedDuration: 12,
    },

    // ========== MATHEMATICS SCENARIOS (Professor Carlos) ==========
    {
        id: 'math-pythagorean',
        avatarId: 'prof-matematica',
        title: 'Teorema de Pitágoras',
        description: 'Aprenda a aplicar o Teorema de Pitágoras em problemas práticos do dia a dia.',
        difficulty: 'beginner',
        category: 'Geometria',
        initialPrompt: `Vamos aprender sobre o Teorema de Pitágoras! Imagine que você precisa calcular a diagonal de uma TV de 40 polegadas. Me diga: você sabe o que é um triângulo retângulo?`,
        learningObjectives: [
            'Entender o Teorema de Pitágoras',
            'Identificar triângulos retângulos',
            'Resolver problemas práticos',
        ],
        estimatedDuration: 15,
    },
    {
        id: 'math-percentage',
        avatarId: 'prof-matematica',
        title: 'Porcentagem no Dia a Dia',
        description: 'Calcule descontos, juros e porcentagens em situações reais.',
        difficulty: 'beginner',
        category: 'Matemática Financeira',
        initialPrompt: `Hoje vamos falar sobre porcentagem! Imagine que você viu uma camisa de R$ 80 com 25% de desconto. Quanto você vai pagar? Vamos resolver juntos!`,
        learningObjectives: [
            'Calcular porcentagens',
            'Entender descontos',
            'Aplicar em situações reais',
        ],
        estimatedDuration: 12,
    },
    {
        id: 'math-equations',
        avatarId: 'prof-matematica',
        title: 'Equações do 2º Grau',
        description: 'Resolva equações quadráticas usando Bhaskara e entenda suas aplicações.',
        difficulty: 'intermediate',
        category: 'Álgebra',
        initialPrompt: `Vamos resolver equações do 2º grau! Você conhece a fórmula de Bhaskara? Vamos começar com um exemplo simples: x² - 5x + 6 = 0`,
        learningObjectives: [
            'Identificar equações do 2º grau',
            'Aplicar fórmula de Bhaskara',
            'Interpretar resultados',
        ],
        estimatedDuration: 20,
    },
    {
        id: 'math-fractions',
        avatarId: 'prof-matematica',
        title: 'Frações na Cozinha',
        description: 'Aprenda frações através de receitas e medidas culinárias.',
        difficulty: 'beginner',
        category: 'Frações',
        initialPrompt: `Vamos aprender frações fazendo um bolo! A receita pede 3/4 de xícara de açúcar, mas você quer fazer metade da receita. Quanto de açúcar você vai usar?`,
        learningObjectives: [
            'Entender frações',
            'Somar e multiplicar frações',
            'Aplicar em receitas',
        ],
        estimatedDuration: 15,
    },
    {
        id: 'math-functions',
        avatarId: 'prof-matematica',
        title: 'Funções e Gráficos',
        description: 'Compreenda funções lineares e como representá-las graficamente.',
        difficulty: 'intermediate',
        category: 'Funções',
        initialPrompt: `Hoje vamos explorar funções! Imagine que um táxi cobra R$ 5 de bandeirada + R$ 2 por km. Como podemos representar isso matematicamente?`,
        learningObjectives: [
            'Entender conceito de função',
            'Criar funções lineares',
            'Interpretar gráficos',
        ],
        estimatedDuration: 18,
    },

    // ========== HISTORY SCENARIOS (Dom Pedro II) ==========
    {
        id: 'hist-independence',
        avatarId: 'dom-pedro-ii',
        title: 'Independência do Brasil',
        description: 'Converse sobre o processo de independência e seus personagens principais.',
        difficulty: 'beginner',
        category: 'Brasil Império',
        initialPrompt: `Saudações! Gostaria de conversar sobre como o Brasil se tornou independente? Meu pai, Dom Pedro I, teve papel fundamental nisso. O que você já sabe sobre o Grito do Ipiranga?`,
        learningObjectives: [
            'Entender o processo de independência',
            'Conhecer personagens históricos',
            'Contextualizar o período',
        ],
        estimatedDuration: 15,
    },
    {
        id: 'hist-abolition',
        avatarId: 'dom-pedro-ii',
        title: 'Abolição da Escravatura',
        description: 'Explore o processo abolicionista e a Lei Áurea.',
        difficulty: 'intermediate',
        category: 'Brasil Império',
        initialPrompt: `A abolição da escravatura foi um dos momentos mais importantes do meu reinado. Minha filha, a Princesa Isabel, assinou a Lei Áurea em 1888. Você sabe o que levou a esse momento histórico?`,
        learningObjectives: [
            'Compreender o abolicionismo',
            'Conhecer leis abolicionistas',
            'Refletir sobre impactos sociais',
        ],
        estimatedDuration: 20,
    },
    {
        id: 'hist-modernization',
        avatarId: 'dom-pedro-ii',
        title: 'Modernização do Brasil',
        description: 'Descubra as inovações tecnológicas e culturais do Segundo Reinado.',
        difficulty: 'intermediate',
        category: 'Brasil Império',
        initialPrompt: `Durante meu reinado, o Brasil passou por grande modernização! Trouxemos ferrovias, telégrafo, iluminação a gás... Eu mesmo fui o primeiro brasileiro a usar um telefone! O que você gostaria de saber sobre essas inovações?`,
        learningObjectives: [
            'Conhecer avanços tecnológicos',
            'Entender modernização do Brasil',
            'Relacionar passado e presente',
        ],
        estimatedDuration: 15,
    },
    {
        id: 'hist-war-paraguay',
        avatarId: 'dom-pedro-ii',
        title: 'Guerra do Paraguai',
        description: 'Entenda as causas, desenvolvimento e consequências da Guerra do Paraguai.',
        difficulty: 'advanced',
        category: 'Conflitos',
        initialPrompt: `A Guerra do Paraguai (1864-1870) foi o maior conflito armado da América do Sul. Foi um período difícil para o Brasil. Você conhece as causas dessa guerra?`,
        learningObjectives: [
            'Compreender causas da guerra',
            'Conhecer principais batalhas',
            'Analisar consequências',
        ],
        estimatedDuration: 25,
    },
    {
        id: 'hist-republic',
        avatarId: 'dom-pedro-ii',
        title: 'Proclamação da República',
        description: 'Reflita sobre o fim do Império e início da República no Brasil.',
        difficulty: 'intermediate',
        category: 'Transição Política',
        initialPrompt: `Em 1889, o Império chegou ao fim e a República foi proclamada. Foi um momento de grande mudança para o Brasil. Você sabe o que levou ao fim da monarquia?`,
        learningObjectives: [
            'Entender causas da proclamação',
            'Conhecer personagens republicanos',
            'Refletir sobre mudanças políticas',
        ],
        estimatedDuration: 18,
    },

    // ========== PORTUGUESE SCENARIOS (Profa. Mariana) ==========
    {
        id: 'port-literatura-classica',
        avatarId: 'profa-mariana',
        title: 'Literatura Clássica Portuguesa',
        description: 'Explore os grandes autores portugueses e suas obras.',
        difficulty: 'intermediate',
        category: 'Literatura',
        initialPrompt: `Olá! Vamos mergulhar no mundo da literatura clássica portuguesa! Você já leu Fernando Pessoa ou Camões? Qual é o seu gênero literário favorito?`,
        learningObjectives: [
            'Conhecer autores clássicos',
            'Entender contexto histórico',
            'Analisar obras literárias',
        ],
        estimatedDuration: 20,
    },
    {
        id: 'port-redacao',
        avatarId: 'profa-mariana',
        title: 'Técnicas de Redação',
        description: 'Aprenda estrutura e técnicas para escrever melhor.',
        difficulty: 'beginner',
        category: 'Escrita',
        initialPrompt: `Vamos melhorar suas habilidades de escrita! Uma boa redação tem introdução, desenvolvimento e conclusão. Qual tema você gostaria de explorar?`,
        learningObjectives: [
            'Estruturar um texto',
            'Argumentar com clareza',
            'Revisar e melhorar',
        ],
        estimatedDuration: 15,
    },
    {
        id: 'port-gramatica',
        avatarId: 'profa-mariana',
        title: 'Gramática Avançada',
        description: 'Domine concordância, regência e pontuação.',
        difficulty: 'intermediate',
        category: 'Gramática',
        initialPrompt: `A gramática é a base do bom português! Hoje vamos trabalhar com concordância nominal e verbal. Você sabe a diferença?`,
        learningObjectives: [
            'Aplicar regras de concordância',
            'Entender regência verbal',
            'Usar pontuação corretamente',
        ],
        estimatedDuration: 18,
    },
    {
        id: 'port-romantismo',
        avatarId: 'profa-mariana',
        title: 'Movimento Romântico',
        description: 'Descubra as características e autores do Romantismo.',
        difficulty: 'intermediate',
        category: 'Movimentos Literários',
        initialPrompt: `O Romantismo foi um movimento apaixonado e emotivo! Machado de Assis, Gonçalves Dias... Que beleza! Você sabe o que caracteriza o Romantismo?`,
        learningObjectives: [
            'Conhecer características do Romantismo',
            'Identificar autores românticos',
            'Analisar poesias românticas',
        ],
        estimatedDuration: 17,
    },

    // ========== SCIENCES SCENARIOS (Prof. Bruno) ==========
    {
        id: 'sci-photosynthesis',
        avatarId: 'prof-bruno',
        title: 'Fotossíntese: Energia do Sol',
        description: 'Descubra como as plantas transformam luz em alimento.',
        difficulty: 'beginner',
        category: 'Biologia',
        initialPrompt: `Opa! Vamos falar de um dos processos mais legais da natureza: a fotossíntese! Você sabe como as plantas fazem seu próprio alimento? Vamos explorar essa magia!`,
        learningObjectives: [
            'Entender fotossíntese',
            'Conhecer fases do processo',
            'Aplicar em ecossistemas',
        ],
        estimatedDuration: 15,
    },
    {
        id: 'sci-dna',
        avatarId: 'prof-bruno',
        title: 'DNA: O Código da Vida',
        description: 'Explore a estrutura e função do DNA.',
        difficulty: 'intermediate',
        category: 'Genética',
        initialPrompt: `DNA é absolutamente fascinante! Aquela moleculinha em forma de hélice contém toda a informação genética de um ser vivo! Você já se perguntou como você herdou características dos seus pais?`,
        learningObjectives: [
            'Compreender estrutura do DNA',
            'Entender replicação e transcrição',
            'Explorar herança genética',
        ],
        estimatedDuration: 18,
    },
    {
        id: 'sci-evolution',
        avatarId: 'prof-bruno',
        title: 'Teoria da Evolução',
        description: 'Entenda como as espécies evoluem ao longo do tempo.',
        difficulty: 'advanced',
        category: 'Evolução',
        initialPrompt: `Darwin mudou nossa compreensão da vida! A evolução por seleção natural é um conceito poderoso. Você já pensou em por que diferentes animais têm características adaptadas ao seu ambiente?`,
        learningObjectives: [
            'Compreender seleção natural',
            'Conhecer evidências evolutivas',
            'Refletir sobre adaptações',
        ],
        estimatedDuration: 20,
    },
    {
        id: 'sci-ecosystems',
        avatarId: 'prof-bruno',
        title: 'Ecossistemas e Biodiversidade',
        description: 'Explore a complexa rede de relações nos ecossistemas.',
        difficulty: 'intermediate',
        category: 'Ecologia',
        initialPrompt: `Os ecossistemas são como cidades vivas! Cada organismo tem um papel importante. Vamos conversar sobre cadeias alimentares, produtores, consumidores... É incrível!`,
        learningObjectives: [
            'Entender cadeias alimentares',
            'Conhecer ciclos biogeoquímicos',
            'Refletir sobre conservação',
        ],
        estimatedDuration: 16,
    },

    // ========== GEOGRAPHY SCENARIOS (Profa. Sofia) ==========
    {
        id: 'geo-climate',
        avatarId: 'profa-sofia',
        title: 'Climas do Mundo',
        description: 'Explore os diferentes climas e suas características.',
        difficulty: 'beginner',
        category: 'Climatologia',
        initialPrompt: `Que aventura vamos ter! Vamos explorar os diferentes climas do nosso planeta: desertos escaldantes, florestas tropicais, regiões polares... Você sabe como os climas são definidos?`,
        learningObjectives: [
            'Classificar diferentes climas',
            'Entender fatores climáticos',
            'Relacionar clima e vegetação',
        ],
        estimatedDuration: 14,
    },
    {
        id: 'geo-continents',
        avatarId: 'profa-sofia',
        title: 'Continentes e Regiões',
        description: 'Descubra a geografia dos continentes e suas regiões.',
        difficulty: 'beginner',
        category: 'Geopolítica',
        initialPrompt: `Vamos viajar pelo mundo! Cada continente tem características únicas: Europa com sua história, Ásia com seu tamanho, América com sua diversidade... Para onde você gostaria de começar nossa exploração?`,
        learningObjectives: [
            'Conhecer continentes e regiões',
            'Entender divisões geopolíticas',
            'Explorar características regionais',
        ],
        estimatedDuration: 15,
    },
    {
        id: 'geo-urbanization',
        avatarId: 'profa-sofia',
        title: 'Urbanização e Cidades',
        description: 'Analise o processo de urbanização e seus impactos.',
        difficulty: 'intermediate',
        category: 'Geografia Urbana',
        initialPrompt: `As cidades crescem cada dia mais! Mas você já parou para pensar nos desafios da urbanização? Enchentes, poluição, desigualdade... Vamos conversar sobre esse fenômeno global?`,
        learningObjectives: [
            'Entender processo de urbanização',
            'Analisar impactos ambientais',
            'Refletir sobre planejamento urbano',
        ],
        estimatedDuration: 16,
    },
    {
        id: 'geo-natural-resources',
        avatarId: 'profa-sofia',
        title: 'Recursos Naturais e Sustentabilidade',
        description: 'Explore recursos naturais e desenvolvimento sustentável.',
        difficulty: 'intermediate',
        category: 'Sustentabilidade',
        initialPrompt: `O planeta tem recursos finitos! Como podemos aproveitar o que temos mantendo a sustentabilidade? Vamos explorar energias renováveis, conservação e desenvolvimento sustentável?`,
        learningObjectives: [
            'Conhecer recursos renováveis e não-renováveis',
            'Entender desenvolvimento sustentável',
            'Refletir sobre impacto humano',
        ],
        estimatedDuration: 17,
    },

    // ========== PHYSICAL EDUCATION SCENARIOS (Prof. Lucas) ==========
    {
        id: 'ed-fitness',
        avatarId: 'prof-lucas',
        title: 'Fitness e Condicionamento',
        description: 'Aprenda sobre treinamento, resistência e saúde cardiovascular.',
        difficulty: 'beginner',
        category: 'Fitness',
        initialPrompt: `Vamos ficar em forma! Você sabe qual é a diferença entre aeróbico e anaeróbico? Vamos conversar sobre exercícios, frequência cardíaca e como criar um treino eficaz!`,
        learningObjectives: [
            'Entender tipos de exercício',
            'Calcular frequência cardíaca',
            'Planejar treinos',
        ],
        estimatedDuration: 14,
    },
    {
        id: 'ed-sports',
        avatarId: 'prof-lucas',
        title: 'Esportes e Competição',
        description: 'Explore diferentes esportes e suas regras.',
        difficulty: 'beginner',
        category: 'Esportes',
        initialPrompt: `Que emoção! Vamos falar sobre esportes! Futebol, basquete, natação... Qual é o seu esporte favorito? Vamos explorar técnicas, regras e história dos esportes?`,
        learningObjectives: [
            'Conhecer diferentes esportes',
            'Entender regras e técnicas',
            'Refletir sobre esporte na sociedade',
        ],
        estimatedDuration: 15,
    },
    {
        id: 'ed-nutrition',
        avatarId: 'prof-lucas',
        title: 'Nutrição e Saúde',
        description: 'Entenda como alimentação e exercício trabalham juntos.',
        difficulty: 'beginner',
        category: 'Nutrição',
        initialPrompt: `Você é o que você come! Uma alimentação balanceada é essencial. Vamos conversar sobre macronutrientes, calorias, hidratação... Como você pode melhorar sua saúde?`,
        learningObjectives: [
            'Compreender nutrientes básicos',
            'Calcular necessidades calóricas',
            'Planejar refeições saudáveis',
        ],
        estimatedDuration: 13,
    },
    {
        id: 'ed-wellbeing',
        avatarId: 'prof-lucas',
        title: 'Bem-estar e Qualidade de Vida',
        description: 'Descubra como exercício contribui para bem-estar mental.',
        difficulty: 'beginner',
        category: 'Saúde Mental',
        initialPrompt: `Exercício não é só para o corpo! O movimento libera endorfinas e melhora nossa saúde mental. Vamos conversar sobre bem-estar integral?`,
        learningObjectives: [
            'Entender saúde holística',
            'Conhecer benefícios do exercício',
            'Refletir sobre equilíbrio vida-trabalho',
        ],
        estimatedDuration: 12,
    },

    // ========== ART SCENARIOS (Mestra Carolina) ==========
    {
        id: 'art-history',
        avatarId: 'mestra-carolina',
        title: 'História da Arte',
        description: 'Explore movimentos artísticos através dos tempos.',
        difficulty: 'intermediate',
        category: 'História',
        initialPrompt: `Que privilégio falar de arte! Da Renascença ao Modernismo, cada período teve suas características. Você prefere arte clássica ou contemporânea? Vamos explorar movimentos artísticos?`,
        learningObjectives: [
            'Conhecer períodos artísticos',
            'Identificar estilos e artistas',
            'Analisar obras de arte',
        ],
        estimatedDuration: 18,
    },
    {
        id: 'art-techniques',
        avatarId: 'mestra-carolina',
        title: 'Técnicas de Pintura e Desenho',
        description: 'Aprenda técnicas fundamentais de artes visuais.',
        difficulty: 'beginner',
        category: 'Técnicas',
        initialPrompt: `Vamos criar arte! Você pode usar aquarela, óleo, acrílico... Cada técnica tem suas características. Quer saber como começar a desenhar ou pintar?`,
        learningObjectives: [
            'Conhecer diferentes materiais',
            'Aprender técnicas básicas',
            'Desenvolver expressão artística',
        ],
        estimatedDuration: 15,
    },
    {
        id: 'art-composition',
        avatarId: 'mestra-carolina',
        title: 'Composição e Perspectiva',
        description: 'Domine as regras de composição visual e perspectiva.',
        difficulty: 'intermediate',
        category: 'Teoria',
        initialPrompt: `Uma boa composição faz toda a diferença! Você sabe sobre a regra dos terços, perspectiva, proporção? Vamos explorar como criar imagens visualmente interessantes?`,
        learningObjectives: [
            'Aplicar regra dos terços',
            'Compreender perspectiva',
            'Equilibrar elementos visuais',
        ],
        estimatedDuration: 16,
    },
    {
        id: 'art-digital',
        avatarId: 'mestra-carolina',
        title: 'Arte Digital e Design',
        description: 'Explore a interseção entre arte e tecnologia.',
        difficulty: 'intermediate',
        category: 'Digital',
        initialPrompt: `A arte é cada vez mais digital! Photoshop, Procreate, Blender... Você tem interesse em explorar arte digital? Vamos conversar sobre esse universo criativo?`,
        learningObjectives: [
            'Conhecer ferramentas digitais',
            'Entender design gráfico',
            'Explorar possibilidades criativas',
        ],
        estimatedDuration: 17,
    },

    // ========== MUSIC SCENARIOS (Maestro Antônio) ==========
    {
        id: 'mus-theory',
        avatarId: 'maestro-antonio',
        title: 'Teoria Musical Básica',
        description: 'Aprenda notas, escalas e acordes fundamentais.',
        difficulty: 'beginner',
        category: 'Teoria',
        initialPrompt: `Bem-vindo ao mundo da música! Vamos começar com o básico: as notas musicais (Dó, Ré, Mi...), escalas, ritmo... Você toca algum instrumento?`,
        learningObjectives: [
            'Conhecer notas e escalas',
            'Entender ritmo e compasso',
            'Formar acordes básicos',
        ],
        estimatedDuration: 14,
    },
    {
        id: 'mus-history',
        avatarId: 'maestro-antonio',
        title: 'História da Música',
        description: 'Explore períodos musicais e grandes compositores.',
        difficulty: 'intermediate',
        category: 'História',
        initialPrompt: `A música acompanha a humanidade há séculos! Bach, Beethoven, Mozart... Cada compositor deixou um legado. Você tem um estilo favorito? Clássico, jazz, rock?`,
        learningObjectives: [
            'Conhecer compositores clássicos',
            'Entender períodos musicais',
            'Explorar diferentes gêneros',
        ],
        estimatedDuration: 16,
    },
    {
        id: 'mus-instruments',
        avatarId: 'maestro-antonio',
        title: 'Instrumentos Musicais',
        description: 'Descubra a variedade de instrumentos e suas características.',
        difficulty: 'beginner',
        category: 'Instrumentos',
        initialPrompt: `Que variedade! Piano, violão, flauta, bateria... Cada instrumento tem seu som único. Qual instrumento você gostaria de aprender ou conhecer melhor?`,
        learningObjectives: [
            'Classificar instrumentos',
            'Conhecer características sonoras',
            'Entender grupos instrumentais',
        ],
        estimatedDuration: 13,
    },
    {
        id: 'mus-composition',
        avatarId: 'maestro-antonio',
        title: 'Composição e Arranjo',
        description: 'Aprenda a compor e arranjar suas próprias músicas.',
        difficulty: 'advanced',
        category: 'Composição',
        initialPrompt: `Quer criar sua própria música? Composição é uma arte! Vamos explorar como estruturar uma música, harmonia, progressões de acordes... Você tem uma melod­ia em mente?`,
        learningObjectives: [
            'Criar progressões harmônicas',
            'Estruturar uma composição',
            'Explorar arranjos',
        ],
        estimatedDuration: 20,
    },

    // ========== PHILOSOPHY SCENARIOS (Sócrates) ==========
    {
        id: 'fil-socratic-method',
        avatarId: 'socrates',
        title: 'Método Socrático',
        description: 'Explore o famoso método de questionamento de Sócrates.',
        difficulty: 'intermediate',
        category: 'Epistemologia',
        initialPrompt: `Saudações, amigo! Eu sou Sócrates. Meu método é simples: perguntar para chegar à verdade. Diga-me, o que é justiça? E como você sabe disso?`,
        learningObjectives: [
            'Entender método socrático',
            'Questionar pressupostos',
            'Buscar definições verdadeiras',
        ],
        estimatedDuration: 18,
    },
    {
        id: 'fil-ethics',
        avatarId: 'socrates',
        title: 'Ética e Virtude',
        description: 'Refita sobre moral, virtude e como viver bem.',
        difficulty: 'intermediate',
        category: 'Ética',
        initialPrompt: `O que é viver bem? O que é virtude? Essas são questões eternas que reflito há séculos. Como você define uma vida virtuosa?`,
        learningObjectives: [
            'Refletir sobre virtude',
            'Entender teorias éticas',
            'Aplicar ética a dilemmas',
        ],
        estimatedDuration: 17,
    },
    {
        id: 'fil-knowledge',
        avatarId: 'socrates',
        title: 'Teoria do Conhecimento',
        description: 'Explore o que é conhecimento e como o adquirimos.',
        difficulty: 'advanced',
        category: 'Epistemologia',
        initialPrompt: `Você acha que sabe, mas sabe realmente? Esse é o começo da sabedoria: reconhecer a própria ignorância. O que você acha que é o conhecimento?`,
        learningObjectives: [
            'Questionar certezas',
            'Explorar tipos de conhecimento',
            'Refletir sobre aprendizado',
        ],
        estimatedDuration: 20,
    },
    {
        id: 'fil-existence',
        avatarId: 'socrates',
        title: 'Existência e Ser',
        description: 'Mergulhe em questões fundamentais sobre existência.',
        difficulty: 'advanced',
        category: 'Metafísica',
        initialPrompt: `Por que existimos? O que significa "ser"? Essas perguntas acompanham os filósofos desde meu tempo. Qual é sua reflexão sobre a existência humana?`,
        learningObjectives: [
            'Explorar questões existenciais',
            'Conhecer diferentes perspectivas',
            'Desenvolver pensamento crítico',
        ],
        estimatedDuration: 22,
    },

    // ========== RELIGION/ETHICS SCENARIOS (Monge Tenzin) ==========
    {
        id: 'rel-buddhism',
        avatarId: 'monge-tenzin',
        title: 'Caminho do Budismo',
        description: 'Aprenda sobre ensinamentos budistas e meditação.',
        difficulty: 'beginner',
        category: 'Religiões',
        initialPrompt: `Bem-vindo! A paz que você busca está dentro de si. O Budismo oferece um caminho para reduzir o sofrimento através da sabedoria e compaixão. Você gostaria de aprender sobre meditação?`,
        learningObjectives: [
            'Conhecer Nobres Verdades',
            'Entender meditação',
            'Explorar caminho do meio',
        ],
        estimatedDuration: 15,
    },
    {
        id: 'rel-compassion',
        avatarId: 'monge-tenzin',
        title: 'Compaixão Universal',
        description: 'Explore o conceito de compaixão em diferentes tradições.',
        difficulty: 'beginner',
        category: 'Ética',
        initialPrompt: `A compaixão é o coração de todas as religiões. Independente de crença, a compaixão nos une. Como você pode desenvolver compaixão em sua vida?`,
        learningObjectives: [
            'Compreender compaixão',
            'Reconhecer interconexão',
            'Praticar bondade amorosa',
        ],
        estimatedDuration: 14,
    },
    {
        id: 'rel-meditation',
        avatarId: 'monge-tenzin',
        title: 'Práticas de Meditação',
        description: 'Descubra diferentes técnicas de meditação e seus benefícios.',
        difficulty: 'beginner',
        category: 'Práticas Espirituais',
        initialPrompt: `A meditação acalma a mente turbulenta. Existem muitas práticas: meditação de atenção plena, visualização, mantras... Você gostaria de começar uma prática?`,
        learningObjectives: [
            'Aprender técnicas básicas',
            'Entender benefícios da meditação',
            'Estabelecer prática regular',
        ],
        estimatedDuration: 12,
    },
    {
        id: 'rel-meaning',
        avatarId: 'monge-tenzin',
        title: 'Significado e Propósito',
        description: 'Reflita sobre significado da vida e propósito pessoal.',
        difficulty: 'intermediate',
        category: 'Filosofia de Vida',
        initialPrompt: `Qual é o propósito da sua vida? Essa é uma pergunta que todos fazemos. Vamos explorar significado, propósito e como viver uma vida plena?`,
        learningObjectives: [
            'Explorar significado pessoal',
            'Refletir sobre valores',
            'Descobrir propósito',
        ],
        estimatedDuration: 18,
    },

    // ========== INFORMATICS SCENARIOS (Dev Ana) ==========
    {
        id: 'it-programming-basics',
        avatarId: 'dev-ana',
        title: 'Fundamentos de Programação',
        description: 'Aprenda conceitos básicos de programação.',
        difficulty: 'beginner',
        category: 'Programação',
        initialPrompt: `Oi! Bem-vindo ao mundo da programação! Tudo em código começa com lógica simples: variáveis, condicionais, loops. Qual linguagem você gostaria de aprender?`,
        learningObjectives: [
            'Compreender lógica de programação',
            'Conhecer estruturas básicas',
            'Escrever primeiro programa',
        ],
        estimatedDuration: 15,
    },
    {
        id: 'it-web-development',
        avatarId: 'dev-ana',
        title: 'Desenvolvimento Web',
        description: 'Crie websites com HTML, CSS e JavaScript.',
        difficulty: 'beginner',
        category: 'Web',
        initialPrompt: `Vamos criar um website! HTML estrutura, CSS deixa bonito, JavaScript torna interativo. Que tipo de site você gostaria de criar?`,
        learningObjectives: [
            'Estruturar HTML',
            'Estilizar com CSS',
            'Adicionar interatividade com JS',
        ],
        estimatedDuration: 18,
    },
    {
        id: 'it-databases',
        avatarId: 'dev-ana',
        title: 'Bancos de Dados',
        description: 'Aprenda SQL e como gerenciar dados.',
        difficulty: 'intermediate',
        category: 'Banco de Dados',
        initialPrompt: `Dados são o ouro do século 21! Vamos aprender SQL: como armazenar, consultar e gerenciar informações. Pronto para explorar bancos de dados?`,
        learningObjectives: [
            'Criar tabelas SQL',
            'Consultar dados',
            'Otimizar performance',
        ],
        estimatedDuration: 17,
    },
    {
        id: 'it-algorithms',
        avatarId: 'dev-ana',
        title: 'Algoritmos e Estruturas de Dados',
        description: 'Domine algoritmos eficientes e estruturas de dados.',
        difficulty: 'advanced',
        category: 'Ciência da Computação',
        initialPrompt: `Um bom algoritmo é eficiente! Vamos explorar busca, ordenação, árvores, grafos... Como você resolveria um problema de forma otimizada?`,
        learningObjectives: [
            'Compreender complexidade',
            'Implementar estruturas de dados',
            'Otimizar soluções',
        ],
        estimatedDuration: 20,
    },

    // ========== SPANISH SCENARIOS (Señorita Isabella) ==========
    {
        id: 'span-conversacion',
        avatarId: 'senorita-isabella',
        title: 'Conversación Cotidiana',
        description: 'Practica español en situaciones del día a día.',
        difficulty: 'beginner',
        category: 'Conversación',
        initialPrompt: `¡Hola, amigo! Bienvenido a mi clase de español. Vamos practicar conversación cotidiana. ¿Cómo estás hoy? ¿De dónde eres?`,
        learningObjectives: [
            'Saludar y presentarse',
            'Conversar sobre rutina',
            'Preguntar y responder preguntas básicas',
        ],
        estimatedDuration: 12,
    },
    {
        id: 'span-culture',
        avatarId: 'senorita-isabella',
        title: 'Cultura Hispana',
        description: 'Explora la cultura, tradiciones y festividades.',
        difficulty: 'intermediate',
        category: 'Cultura',
        initialPrompt: `¿Quieres conocer la riqueza de la cultura hispana? España, México, Colombia, Argentina... Cada país tiene tradiciones únicas. ¿Cuál te interesa?`,
        learningObjectives: [
            'Conocer tradiciones hispanohablantes',
            'Entender diferencias culturales',
            'Apreciar diversidad',
        ],
        estimatedDuration: 15,
    },
    {
        id: 'span-grammar',
        avatarId: 'senorita-isabella',
        title: 'Gramática Española',
        description: 'Domina verbos conjugaciones y estructura.',
        difficulty: 'intermediate',
        category: 'Gramática',
        initialPrompt: `La gramática española es fascinante! Verbos irregulares, tiempos complejos, subjuntivo... ¿Qué tema gramatical te desafía más?`,
        learningObjectives: [
            'Conjugar verbos irregulares',
            'Usar tiempos verbales',
            'Construir frases complejas',
        ],
        estimatedDuration: 16,
    },
    {
        id: 'span-travel',
        avatarId: 'senorita-isabella',
        title: 'Viajar por Hispanoamérica',
        description: 'Practica español para viajar y relacionarte con locales.',
        difficulty: 'beginner',
        category: 'Viajes',
        initialPrompt: `¿Quieres viajar por el mundo hispano? Vamos a practicar: cómo pedir direcciones, reservar hotel, ordenar comida... ¿A dónde te gustaría ir?`,
        learningObjectives: [
            'Vocabulario de viajes',
            'Pedir direcciones',
            'Interactuar en situaciones turísticas',
        ],
        estimatedDuration: 13,
    },
];

// Helper functions
export function getScenariosByAvatar(avatarId: string): Scenario[] {
    return SCENARIOS.filter(s => s.avatarId === avatarId);
}

export function getScenarioById(id: string): Scenario | undefined {
    return SCENARIOS.find(s => s.id === id);
}

export function getScenariosByDifficulty(difficulty: Scenario['difficulty']): Scenario[] {
    return SCENARIOS.filter(s => s.difficulty === difficulty);
}

export function getScenariosByCategory(category: string): Scenario[] {
    return SCENARIOS.filter(s => s.category === category);
}

